-- Ex 3 - Crie Tabela Proprietário - Nome, Sobrenome e Endereço

CREATE TABLE PROPRIETARIO (
		NOME VARCHAR(20),
		SOBRENOME VARCHAR(40),
		ENDERECO VARCHAR(120)
)

-- Ex 4 - Crie tabela Imovel - Tipo de Imóvel, Valor, Observações, Detalhes, Endereço

CREATE TABLE IMOVEL (
		TIPO_IMOVEL VARCHAR(10),
		VALOR MONEY,
		OBSERVACOES VARCHAR(200),
		DETALHES VARCHAR (100),
		ENDERECO VARCHAR (150)
)

-- Ex 5 - Defina Chave Primaria na tabela Proprietário

DROP TABLE PROPRIETARIO

CREATE TABLE PROPRIETARIO (
		NOME VARCHAR(20),
		SOBRENOME VARCHAR(40),
		ENDERECO VARCHAR(120),
		ID INT PRIMARY KEY
)

-- Ex 6 - Defina Chave Primaria na Tabela Imóvel

ALTER TABLE IMOVEL ADD COLUMN ID INT PRIMARY KEY

-- Ex 7 - Alter table na tabela Proprietário

ALTER TABLE PROPRIETARIO ADD COLUMN TELEFONE VARCHAR(20)
ALTER TABLE PROPRIETARIO ADD COLUMN ENDERECO_TRABALHO VARCHAR(150)

-- Ex 8 - Alter table na tabela Imóvel

ALTER TABLE IMOVEL DROP COLUMN DETALHES

-- Ex 9 - Relacione a tabela Proprietário com a tabela Imóvel

ALTER TABLE IMOVEL 	ADD COLUMN ID_PROPRIETARIO INT
ALTER TABLE IMOVEL 	ADD CONSTRAINT FK_ID_PROPRIETARIO 
					FOREIGN KEY (ID_PROPRIETARIO)
					REFERENCES PROPRIETARIO(ID)

-- Ex 10 - Crei o script para excluir as tabelas Proprietário e Imóvel

DROP TABLE PROPRIETARIO
DROP TABLE IMOVEL